apiVersion: v1
kind: Pod
metadata:
  name: pod-apps
  labels:
    env: prod
    app: main
    tier: frontend
    owner: yaburov
spec:
  containers:
    - name: container-flask
      # nginx:latest  httpd:latest tomcat:latest
      # you could change image only without delete pod
      image: yaburov/flask-app:2
      ports:
        - containerPort: 8080
    - name: container-php
      # nginx:latest  httpd:latest tomcat:latest
      # you could change image only without delete pod
      image: yaburov/php-sample:0.2
      ports:
        - containerPort: 80